#page title
page_title: Pi

# Information About Yourself
your_name: Pi Discord bot
your_link: https://pi-bot.netlify.app
your_city: Toronto
github_username: yak-fumblepack/pi

app_icon: assets/Pi.png
app_description: "Pi is a discord bot for those interested in contest math to practice their skills while engaging in a casual conversation with their fellow mathematicians or friends."

logo: assets/Pi.png

author: Mike Liang

url: "https://pi-bot.netlify.app"

base_url: ""

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Open source!
    description: Any bugs you see? Want to add a feature? Make a pull request and Voil√°!
    fontawesome_icon_name: code-branch

  - title: Limitless practice problems
    description: All sourced from various contests around the globe, AMC, CMO, USAMO, AIME (HMMT, Pascal, Cayley, Fermat coming soon).
    fontawesome_icon_name: infinity

  - title: Robust scoring system
    description: "View your statistics and compete against people in your server for the # position on the leaderboard!"
    fontawesome_icon_name: plus

  - title: Beautifully rendered LaTeX
    description: "Most problems display problem statements rendered with LaTeX to produce stunning math equations."
    fontawesome_icon_name: square-root-alt

  - title: Got a question?
    description: "Join our support and community server <a href='https://discord.com/invite/FrdqSyzg4t'>here</a>! For more information on how to use the bot, type <code>=help</code>"
    fontawesome_icon_name: question

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png # Replace with alternative image path or image URL.
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: coral # Set to: blue, black, yellow, coral or white.

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
